In [1]:
import cv2
import numpy as np

In [2]:
image = cv2.imread('Rithik photo.jpg',1)

In [3]:
print(image)

[[[168 165 161]
  [229 229 229]
  [248 251 255]
  ...
  [187 160 110]
  [208 186 150]
  [241 221 196]]

 [[157 144 136]
  [151 140 136]
  [202 196 197]
  ...
  [193 166 116]
  [189 164 124]
  [187 164 132]]

 [[175 149 137]
  [167 147 136]
  [151 135 129]
  ...
  [199 170 119]
  [195 166 121]
  [186 157 118]]

 ...

 [[142 151 201]
  [ 90 100 140]
  [ 85  98 124]
  ...
  [136 130 149]
  [117 111 134]
  [109 103 128]]

 [[169 174 223]
  [ 95 104 141]
  [ 80  89 109]
  ...
  [184 180 192]
  [161 157 176]
  [146 140 165]]

 [[161 165 214]
  [ 93 100 133]
  [ 69  77  94]
  ...
  [202 202 208]
  [197 192 207]
  [165 158 179]]]


In [4]:
image.shape

(288, 288, 3)

In [98]:
cv2.imshow('Rithik photo', image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [125]:
image = cv2.imread('Rithik photo.jpg')
image = cv2.resize(image,(1000,1000))
cv2.imshow('Rithik photo',image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [126]:
image=cv2.imread('Rithik photo.jpg')
image=cv2.resize(image,(1000,1000))
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Rithik image', gray_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [106]:
image.shape[0]*0.5

500.0

In [107]:
image.shape[1]*0.5

500.0

### Loading CascadeClassifier for detecting faces

In [127]:
face_classifier = cv2.CascadeClassifier("C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")
print(face_classifier)

< cv2.CascadeClassifier 000001454E39E4D0>


In [128]:
face_classifier = cv2.CascadeClassifier("C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")

image = cv2.imread('Rithik photo.jpg')
image = cv2.resize(image,(690,690))
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

#Tuning Cascade Classifiers - detect MultiScale (input image, **Scale Factor**, **Min Neighbors**)
faces = face_classifier.detectMultiScale (gray_image, 1.05, 5)

In [129]:
print(faces)

[[237 165 224 224]]


###  Detecting faces in a gray scale image 

In [131]:
if faces is ():
    print('No faces found')
    
for (x,y,w,h) in faces :
    cv2.rectangle(gray_image,(x,y),(x+w,y+h),(0,255,255),3)
cv2.imshow('Face Detection',gray_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\karth\AppData\Local\Temp\ipykernel_12216\2916019680.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


###  Detecting faces in a color image

In [132]:
if faces is ():
    print('No faces found')
    
for (x,y,w,h) in faces :
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),3)
cv2.imshow('Face Detection',image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\karth\AppData\Local\Temp\ipykernel_12216\3249199254.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


### Loading Cascade Classifer for both Faces and Eyes

In [133]:
face_classifier = cv2.CascadeClassifier("C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("C:/Users/karth/Downloads/haarcascade_eye.xml")


### Detected 1 face for a color Image

### Facial and Eyes Recogniion

In [134]:
image = cv2.imread('Rithik photo.jpg')
image =cv2.resize(image,(670,670))
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(image,1.1,5)

if len(faces) == 0:
    print('no faces found')
    
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray_image[y:y+h,x:x+w]
    roi_color = image[y:y+h,x:x+w]
    
    # detects eyes within the face region
    eyes = eye_classifier.detectMultiScale(roi_gray, scaleFactor = 1.1, minNeighbors = 3)
    
    # Drawing rectangles around each detected eye
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        
cv2.imshow('img',image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

### Detected 1 face in a gray scale image

In [135]:
image= cv2.imread('Rithik photo.jpg')
image =cv2.resize(image,(670,670))
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray_image, 1.3, 5)

if faces is ():
    print('no faces found')
    
for (x,y,w,h) in faces:
    cv2.rectangle(gray_image,(x,y),(x+w,y+h),(0,255,0),3)
    roi_gray = gray_image[y:y+h,x:x+w]
    roi_color = image[y:y+h,x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_gray,(ex,ey),(ex+ew,ey+eh),(0,255,0),3)
        
cv2.imshow('image',gray_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\karth\AppData\Local\Temp\ipykernel_12216\379313312.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


### capturing a video

### Capture video from a webcam or video file using cv2.VideoCapture().

### 1. Process each frame by converting it to grayscale and detecting faces using the Haar Cascade.
### 2. Draw rectangles around the detected faces.
### 3. Display the frame with the detected faces in real time.

In [49]:
# Face Recognition with the webcam

import cv2
video = cv2.VideoCapture(0) #0 indicates for webcam

while True:
    check, frame = video.read() # reads the frame from the webcam
    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #converts the frame to grayscale
    cv2.imshow('web cam', gray_image)
    if cv2.waitKey(1) == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

### Fine-tuning the MultiScale Parameters using Scale Factors and minNeighbors

In [50]:
import cv2

# Load the face classifier
face_classifier = cv2.CascadeClassifier(r"C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")

# Starts capturing video from the webcam
video = cv2.VideoCapture(0) 

while True:
    # Captures the video frame by frame
    check, frame = video.read()
    
    if not check:
        print("Failed to capture video frame.")
        break

    # Converting the frame to grayscale
    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detecting faces in the grayscale frame
    faces = face_classifier.detectMultiScale(gray_image, scaleFactor=1.3, minNeighbors=5)

    # Drawing rectangles around each face detected
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)

    # Displaying the frame with the detected faces
    cv2.imshow('Webcam - Face Detection', frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


video.release()
cv2.destroyAllWindows()

##### First we need to perform the face detection on the grayscale image, but the imshow() function displays the original colored frame. 

##### This is a typical workflow in OpenCV since face detection algorithms often work faster and more effectively in grayscale, while the visualization can be done in color.

In [41]:
import cv2

# Loading the face classifier
face_classifier = cv2.CascadeClassifier(r"C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")

video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    
    if not check:
        print("Failed to capture video frame.")
        break

    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face_classifier.detectMultiScale(gray_image, scaleFactor=1.3, minNeighbors=5)

    for (x, y, w, h) in faces:
        cv2.rectangle(gray_image, (x, y), (x + w, y + h), (255, 0, 0), 2)
        
    cv2.imshow('Webcam - Face Detection', gray_image)

    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

# Let's detect both faces and eyes

##### we need to perform the Cascades for detecting Faces first, and then for Eyes within the detected Face region

In [43]:
import cv2

face_classifier = cv2.CascadeClassifier(r"C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier(r"C:/Users/karth/Downloads/haarcascade_eye.xml")

video = cv2.VideoCapture(0) 

while True:
    check, frame = video.read()

    if not check:
        print("Failed to capture video frame.")
        break

    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_classifier.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=2)

   
    for (x, y, w, h) in faces:
    
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)

        roi_gray = gray_image[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]


        eyes = eye_classifier.detectMultiScale(roi_gray, scaleFactor=1.3, minNeighbors=2)


        for (ex, ey, ew, eh) in eyes:

            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)

    cv2.imshow('Webcam - Face and Eye Detection', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()


# Body Classifier

In [68]:
import cv2

body_classifier = cv2.CascadeClassifier("C:/Users/karth/Downloads/haarcascade_fullbody.xml")


#Initiating the captured video for video file
video = cv2.VideoCapture("C:/Users/karth/Downloads/walking.avi")


while video.isOpened():
    
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray, 1.2, 3)
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w, y+h), (0, 255, 255), 2)
        cv2. imshow('Pedestrians', frame)
        
    if cv2.waitKey(1) == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

In [70]:
import cv2

body_classifier = cv2.CascadeClassifier("C:/Users/karth/Downloads/haarcascade_fullbody.xml")


#Initiate the captured video for video file
video = cv2.VideoCapture("C:/Users/karth/OneDrive - Michigan Technological University/Git Hub Projects/Data Sets/video1.mp4")

#Loop once video is successfully Loaded

while video.isOpened():
    
    #read first frame
    
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray, 1.1, 3)
    
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w, y+h), (0, 255, 255), 2)
        cv2. imshow('Pedestrians', frame)
        
    if cv2.waitKey(1) == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

# Facial and Eye Detection in a Video Capture

In [72]:
import cv2

# Load Haar Cascades for face and eye detection
face_classifier = cv2.CascadeClassifier(r"C:/Users/karth/Downloads/haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier(r"C:/Users/karth/Downloads/haarcascade_eye.xml")

# Start capturing video from the webcam
video = cv2.VideoCapture("C:/Users/karth/OneDrive - Michigan Technological University/Git Hub Projects/Data Sets/video1.mp4")  # 0 indicates the default webcam

while True:
    # Capture the video frame by frame
    check, frame = video.read()

    if not check:
        print("Failed to capture video frame.")
        break

    # Convert the frame to grayscale for face and eye detection
    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detect faces in the grayscale frame
    faces = face_classifier.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=2)

    # Loop through each detected face
    for (x, y, w, h) in faces:
        # Draw rectangle around the face
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)

        # Region of interest for face (to detect eyes within the face)
        roi_gray = gray_image[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]

        # Detect eyes within the face region
        eyes = eye_classifier.detectMultiScale(roi_gray, scaleFactor=1.3, minNeighbors=2)

        # Loop through each detected eye
        for (ex, ey, ew, eh) in eyes:
            # Draw rectangle around each eye (fix applied here)
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)  # Corrected here!

    # Display the frame with detected faces and eyes
    cv2.imshow('Webcam - Face and Eye Detection', frame)

    # Exit when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture object and close all windows
video.release()
cv2.destroyAllWindows()